% RUN_LAPLACE_RESONANCE
% Reconstructed Octave study of the Io-Europa-Ganymede Laplace resonance.
%
% Two cases are generated by default:
%   1) physical Europa mass
%   2) Europa mass multiplied by 100
%
% Output CSV files and PNG plots are written to ../results/.

clear;
close all;
clc;

script_dir = fileparts(mfilename('fullpath'));
addpath(script_dir);
output_dir = fullfile(script_dir, '..', 'results');

if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

mass_factors = [1, 100];
n_ganymede_orbits = 40;
dt = 1.0e-3;
write_every = 50;

for case_index = 1:length(mass_factors)
    factor = mass_factors(case_index);
    fprintf('Running Europa mass factor = %g ...\n', factor);

    result = simulate_laplace(factor, n_ganymede_orbits, dt, write_every);

    % Convert normalized time to days for presentation.
    time_days = result.time * result.time_scale_s / (24 * 3600);

    % Extract sampled x-y coordinates.
    x_jupiter = squeeze(result.positions(:, 1, 1));
    y_jupiter = squeeze(result.positions(:, 1, 2));
    x_io = squeeze(result.positions(:, 2, 1));
    y_io = squeeze(result.positions(:, 2, 2));
    x_europa = squeeze(result.positions(:, 3, 1));
    y_europa = squeeze(result.positions(:, 3, 2));
    x_ganymede = squeeze(result.positions(:, 4, 1));
    y_ganymede = squeeze(result.positions(:, 4, 2));

    e_io = result.eccentricity(:, 2);
    e_europa = result.eccentricity(:, 3);
    e_ganymede = result.eccentricity(:, 4);

    a_io = result.semi_major_axis(:, 2);
    a_europa = result.semi_major_axis(:, 3);
    a_ganymede = result.semi_major_axis(:, 4);

    % Save a compact CSV file.
    csv_path = fullfile(output_dir, sprintf('laplace_mass_factor_%g.csv', factor));
    fid = fopen(csv_path, 'w');
    fprintf(fid, ['time_days,x_jupiter,y_jupiter,x_io,y_io,x_europa,y_europa,' ...
                  'x_ganymede,y_ganymede,a_io,e_io,a_europa,e_europa,a_ganymede,e_ganymede\n']);
    for i = 1:length(time_days)
        fprintf(fid, '%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g\n', ...
            time_days(i), x_jupiter(i), y_jupiter(i), x_io(i), y_io(i), ...
            x_europa(i), y_europa(i), x_ganymede(i), y_ganymede(i), ...
            a_io(i), e_io(i), a_europa(i), e_europa(i), a_ganymede(i), e_ganymede(i));
    end
    fclose(fid);

    % Orbital trajectories.
    fig1 = figure('visible', 'off');
    hold on;
    plot(x_jupiter, y_jupiter, 'k.');
    plot(x_io, y_io);
    plot(x_europa, y_europa);
    plot(x_ganymede, y_ganymede);
    axis equal;
    grid on;
    xlabel('x (normalized distance)');
    ylabel('y (normalized distance)');
    title(sprintf('Galilean orbits, Europa mass factor = %g', factor));
    legend('Jupiter', 'Io', 'Europa', 'Ganymede', 'location', 'best');
    print(fig1, fullfile(output_dir, sprintf('orbits_mass_factor_%g.png', factor)), '-dpng', '-r150');
    close(fig1);

    % Eccentricity evolution.
    fig2 = figure('visible', 'off');
    hold on;
    plot(time_days, e_io);
    plot(time_days, e_europa);
    plot(time_days, e_ganymede);
    grid on;
    xlabel('Time (days)');
    ylabel('Osculating eccentricity');
    title(sprintf('Eccentricity evolution, Europa mass factor = %g', factor));
    legend('Io', 'Europa', 'Ganymede', 'location', 'best');
    print(fig2, fullfile(output_dir, sprintf('eccentricity_mass_factor_%g.png', factor)), '-dpng', '-r150');
    close(fig2);

    fprintf('  Saved %s\n', csv_path);
end

fprintf('Done. Results are in: %s\n', output_dir);
